// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// check_spec
arma::mat check_spec(const arma::vec& la, const arma::vec& mu, const arma::vec& g, const arma::vec& m_prop, const arma::vec& nu, const arma::vec& tau, const arma::vec& xi, int np, int nstep);
RcppExport SEXP _abundolism_check_spec(SEXP laSEXP, SEXP muSEXP, SEXP gSEXP, SEXP m_propSEXP, SEXP nuSEXP, SEXP tauSEXP, SEXP xiSEXP, SEXP npSEXP, SEXP nstepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type la(laSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m_prop(m_propSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< int >::type nstep(nstepSEXP);
    rcpp_result_gen = Rcpp::wrap(check_spec(la, mu, g, m_prop, nu, tau, xi, np, nstep));
    return rcpp_result_gen;
END_RCPP
}
// sim_spec_abund
arma::mat sim_spec_abund(const arma::vec& la, const arma::vec& mu, const arma::vec& g, const arma::vec& m_prop, const arma::vec& nu, const arma::vec& tau, const arma::vec& xi, int np, int nstep);
RcppExport SEXP _abundolism_sim_spec_abund(SEXP laSEXP, SEXP muSEXP, SEXP gSEXP, SEXP m_propSEXP, SEXP nuSEXP, SEXP tauSEXP, SEXP xiSEXP, SEXP npSEXP, SEXP nstepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type la(laSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m_prop(m_propSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< int >::type nstep(nstepSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_spec_abund(la, mu, g, m_prop, nu, tau, xi, np, nstep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_abundolism_check_spec", (DL_FUNC) &_abundolism_check_spec, 9},
    {"_abundolism_sim_spec_abund", (DL_FUNC) &_abundolism_sim_spec_abund, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_abundolism(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
