# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_spec <- function(la, mu, g, m_prop, nu, tau, xi, np, nstep) {
    .Call(`_abundolism_check_spec`, la, mu, g, m_prop, nu, tau, xi, np, nstep)
}

sim_spec_abund <- function(la, mu, g, m_prop, nu, tau, xi, np, nstep) {
    .Call(`_abundolism_sim_spec_abund`, la, mu, g, m_prop, nu, tau, xi, np, nstep)
}

