# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_rates <- function(la, r, np) {
    .Call(`_abundolism_calc_rates`, la, r, np)
}

ewise <- function(g, m_prop) {
    .Call(`_abundolism_ewise`, g, m_prop)
}

sfull_test <- function(np) {
    .Call(`_abundolism_sfull_test`, np)
}

rexp_test <- function(rate) {
    .Call(`_abundolism_rexp_test`, rate)
}

bias_sample <- function(weights) {
    .Call(`_abundolism_bias_sample`, weights)
}

check_probs <- function() {
    .Call(`_abundolism_check_probs`)
}

sim_spec_abund <- function(la, mu, g, m_prop, nu, tau, xi, np, nstep) {
    .Call(`_abundolism_sim_spec_abund`, la, mu, g, m_prop, nu, tau, xi, np, nstep)
}

